### PR TITLE
fix issue #360

### PR DESCRIPTION
**Pull request by fenollp**
Please activate your free Travis account at https://travis-ci.org/kevinlawler/kona/settings

### CODE REVIEW

**Comment by fenollp** [comment]
@tavmem https://travis-ci.org/kevinlawler/kona doesn't seem to be activated yet

**Comment by tavmem** [comment]
Please proceed with the activation (if you wish to use Travis for your
testing of Kona).

**Comment by fenollp** [comment]
That needs to be done by @kevinlawler on travis-ci.org/kevinlawler

**Comment by kevinlawler** [comment]
I authed it so it exists now. If there are other steps please spell them out for me.

**Comment by fenollp** [comment]
1. Go to https://travis-ci.org/profile/kevinlawler
1. click Sync account (top right)
1. "flick" kevinlawler/kona from x to v
1. https://travis-ci.org/kevinlawler/kona shouldn't say "not activated" anymore

then a push/new PR should trigger a Travis build

**Comment by kevinlawler** [comment]
done

**Pull request merged**
